"""create tables

Revision ID: 088e8baa95a7
Revises: 1b138d92902c
Create Date: 2020-02-08 13:40:48.081634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088e8baa95a7'
down_revision = '1b138d92902c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('askue_reg_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=512), nullable=False),
    sa.Column('fes', sa.String(length=25), nullable=False),
    sa.Column('res', sa.String(length=50), nullable=False),
    sa.Column('ps', sa.String(length=50), nullable=False),
    sa.Column('vl', sa.String(length=50), nullable=False),
    sa.Column('rv', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_askue_reg_point_object_name'), 'askue_reg_point', ['object_name'], unique=False)
    op.create_index(op.f('ix_askue_reg_point_rv'), 'askue_reg_point', ['rv'], unique=False)
    op.create_table('askue_rs_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=512), nullable=False),
    sa.Column('fes', sa.String(length=25), nullable=False),
    sa.Column('res', sa.String(length=50), nullable=False),
    sa.Column('ps', sa.String(length=50), nullable=False),
    sa.Column('vl', sa.String(length=50), nullable=False),
    sa.Column('tp', sa.String(length=50), nullable=False),
    sa.Column('sch', sa.String(length=50), nullable=False),
    sa.Column('rv', sa.BigInteger(), nullable=False),
    sa.Column('str_ra', sa.Float(), nullable=False),
    sa.Column('rxx', sa.Float(), nullable=False),
    sa.Column('ktt', sa.Float(), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_askue_rs_point_object_name'), 'askue_rs_point', ['object_name'], unique=False)
    op.create_index(op.f('ix_askue_rs_point_rv'), 'askue_rs_point', ['rv'], unique=False)
    op.create_table('calc_balance',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('id_tu', sa.Integer(), nullable=False),
    sa.Column('dtp', sa.String(length=10), nullable=False),
    sa.Column('locality', sa.String(length=40), nullable=False),
    sa.Column('name_of_accounting_point', sa.String(length=40), nullable=False),
    sa.Column('str_ra', sa.Integer(), nullable=False),
    sa.Column('pxx', sa.Float(), nullable=False),
    sa.Column('loss_xx', sa.Float(), nullable=False),
    sa.Column('ktt', sa.Integer(), nullable=False),
    sa.Column('head_of_counter', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.Float(), nullable=False),
    sa.Column('q_slim', sa.Integer(), nullable=False),
    sa.Column('time_start_write', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calc_reg_balance',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('id_tu', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.Float(), nullable=False),
    sa.Column('time_start_write', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calc_reg_balance')
    op.drop_table('calc_balance')
    op.drop_index(op.f('ix_askue_rs_point_rv'), table_name='askue_rs_point')
    op.drop_index(op.f('ix_askue_rs_point_object_name'), table_name='askue_rs_point')
    op.drop_table('askue_rs_point')
    op.drop_index(op.f('ix_askue_reg_point_rv'), table_name='askue_reg_point')
    op.drop_index(op.f('ix_askue_reg_point_object_name'), table_name='askue_reg_point')
    op.drop_table('askue_reg_point')
    # ### end Alembic commands ###
